// Supabase Edge Function: sync-instagram
//
// Pulls recent posts from the @solace.executive Instagram Business account
// via the Instagram API and upserts them into public.instagram_posts, so
// the homepage gallery updates itself whenever a new photo goes up.
//
// Same pattern as sync-empty-legs: verify_jwt is off so pg_cron can call
// it without a Supabase JWT, guarded instead by a shared secret header.
//
// Requires these secrets (Edge Functions -> Secrets):
//   SUPABASE_SERVICE_ROLE_KEY — Project Settings -> API -> service_role
//   SYNC_SECRET               — same value used by sync-empty-legs
//   INSTAGRAM_ACCESS_TOKEN    — long-lived token from the Instagram API
//                               setup page (Meta for Developers). Expires
//                               after ~60 days and must be regenerated by
//                               hand there when it does.
//   INSTAGRAM_ACCOUNT_ID      — the numeric Instagram Business Account id
// SUPABASE_URL is already injected automatically by Supabase.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.110.2?bundle';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const SYNC_SECRET = Deno.env.get('SYNC_SECRET')!;
const INSTAGRAM_ACCESS_TOKEN = Deno.env.get('INSTAGRAM_ACCESS_TOKEN')!;
const INSTAGRAM_ACCOUNT_ID = Deno.env.get('INSTAGRAM_ACCOUNT_ID')!;
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const MAX_POSTS = 12;

type IgMedia = {
  id: string;
  caption?: string;
  media_type: 'IMAGE' | 'VIDEO' | 'CAROUSEL_ALBUM';
  media_url?: string;
  thumbnail_url?: string;
  permalink: string;
  timestamp: string;
};

Deno.serve(async (req) => {
  if (req.headers.get('x-sync-secret') !== SYNC_SECRET) {
    return new Response(JSON.stringify({ ok: false, error: 'unauthorized' }), { status: 401 });
  }
  try {
    const fields = 'id,caption,media_type,media_url,thumbnail_url,permalink,timestamp';
    const url =
      `https://graph.instagram.com/v21.0/${INSTAGRAM_ACCOUNT_ID}/media` +
      `?fields=${fields}&limit=${MAX_POSTS}&access_token=${INSTAGRAM_ACCESS_TOKEN}`;

    const res = await fetch(url);
    const body = await res.json();
    if (!res.ok) {
      return new Response(JSON.stringify({ ok: false, error: body?.error?.message || `Fetch failed: ${res.status}` }), {
        status: 502,
      });
    }

    const posts: IgMedia[] = (body.data || []).filter((m: IgMedia) => m.media_type !== 'VIDEO' || m.thumbnail_url);

    const rows = posts.map((m) => ({
      media_id: m.id,
      media_type: m.media_type,
      media_url: m.media_type === 'VIDEO' ? m.thumbnail_url : m.media_url,
      permalink: m.permalink,
      caption: m.caption || null,
      posted_at: m.timestamp,
      active: true,
    }));

    if (rows.length > 0) {
      const { error: upsertError } = await supabase.from('instagram_posts').upsert(rows, { onConflict: 'media_id' });
      if (upsertError) throw upsertError;

      const keptIds = rows.map((r) => r.media_id);
      const { error: deleteError } = await supabase
        .from('instagram_posts')
        .delete()
        .not('media_id', 'in', `(${keptIds.map((id) => `"${id}"`).join(',')})`);
      if (deleteError) throw deleteError;
    }

    return new Response(JSON.stringify({ ok: true, synced: rows.length }), {
      headers: { 'content-type': 'application/json' },
    });
  } catch (e) {
    return new Response(JSON.stringify({ ok: false, error: String(e) }), {
      status: 500,
      headers: { 'content-type': 'application/json' },
    });
  }
});
