-- Run in the Supabase SQL Editor after the `public.villas` table (see
-- supabase-schema.sql) has been created. Photo URLs assume the website's
-- assets/photos/villas/ folder has been pushed live at solaceexecutive.com.
-- price_from is left null for all of these (no confirmed rate yet) -- the
-- 10% markup rule applies whenever Kluiver enters an actual rate later,
-- same as yachts.

insert into public.villas (name, area, bedrooms, bathrooms, max_guests, has_pool, living_area_m2, plot_area_m2, description, amenities, price_from, photo_path, photos, sort_order) values

('Villa San Antonio', 'San Antonio', 5, 4, 10, true, 360, null,
 'Een modern huis over twee verdiepingen, verscholen achter bougainville en palmbomen in San Antonio. Ontworpen voor grote gezelschappen zonder concessies aan privacy: het hoofdhuis wordt aangevuld met een zelfstandige tweekamer-annex, rondom een zonnig terras met privézwembad. Binnen vindt u eigentijdse interieurs, een volledig uitgeruste keuken, open haard en smart-tv''s door het hele huis, met het bruisende San Rafael en Ibiza-Stad op enkele minuten afstand.',
 array['Privézwembad met zonneterras','Aangelegde tuin met overdekte pergola-lounge','Zelfstandige tweekamer-annex voor extra privacy','Volledig uitgeruste keuken met vaatwasser en koffiemachine','Airconditioning, centrale verwarming en open haard','Barbecue en tafeltennistafel','5 minuten lopen naar UNVRS','Minuten van San Rafael en Ibiza-Stad'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/hero.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/pool.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/view-aerial.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/dining.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/bedroom-2.jpg','https://solaceexecutive.com/assets/photos/villas/villa-san-antonio/bathroom.jpg'],
 10),

('Villa Nilo', 'Roca Llisa', 5, 5, 10, true, null, null,
 'Gelegen in het afgesloten Roca Llisa met uitzicht over de golfbaan, is Villa Nilo een gedurfd, eigentijds toevluchtsoord voor groepen die ruimte en energie zoeken zonder in te leveren op privacy. Lichte, open leefruimtes lopen door naar een privézwembad, terwijl een dakterras met jacuzzi, lounge en eethoek een weids uitzicht over de heuvels biedt. Een aparte clubruimte met eigen bar en DJ-opstelling maakt het geheel compleet, of het nu gaat om een rustige gezinsweek of een onvergetelijk weekend met vrienden.',
 array['Privézwembad','Dakterras met jacuzzi, lounge en eethoek','Aparte clubruimte met bar en DJ-booth','Afgesloten Roca Llisa met uitzicht over de golfbaan','Lichte, open leef- en eetruimtes','Aangelegde tuin met volwassen bomen en bougainville','Privéparkeerplaats voor meerdere auto''s','Minuten van Ibiza-Stad, Santa Eulalia en Cala Olivera'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/villa-nilo/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/villa-nilo/hero.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/pool.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/dining.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/rooftop-terrace.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/bedroom-2.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/bathroom.jpg','https://solaceexecutive.com/assets/photos/villas/villa-nilo/garden.jpg'],
 20),

('Villa Alfa', 'Es Canar, oostkust', 5, 5, 10, true, 846, 17300,
 'Een eigentijds toevluchtsoord aan de oostkust van Ibiza, gelegen op een uitgestrekt perceel te midden van dennenbos. Strakke architectonische lijnen, dubbelhoge beglazing en een lift naar alle drie de verdiepingen geven deze villa een moeiteloze, resortachtige uitstraling. Gasten genieten van een eigen fitnessruimte, een chill-out terras omgeven door volwassen bomen en interieurs baadend in natuurlijk licht.',
 array['Verwarmd privézwembad met zonneterras','Eigen fitnessruimte en lift naar alle verdiepingen','Overdekt terras voor diner buiten met ingebouwde BBQ','Volledig uitgeruste designkeuken','Vijf en-suite slaapkamers, de meeste met eigen terras','Tweede zitruimte met loungehoek en thuiswerkplek','Airconditioning, wifi en geluidsinstallatie door het hele huis','Privéparkeren op een perceel van 17.300 m² dennenbos'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/villa-alfa/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/villa-alfa/hero.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/exterior.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/pool-terrace.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/bathroom.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/relax-lounge.jpg','https://solaceexecutive.com/assets/photos/villas/villa-alfa/gym.jpg'],
 30),

('Villa Prada', 'Talamanca, Jesús', 7, 5, 14, true, null, null,
 'Een gedurfde, kunstzinnige villa in het geliefde Talamanca, op enkele minuten van Ibiza-Stad. Verspreid over vijf karaktervolle niveaus combineren de interieurs kleurrijke statement-stukken met speels design, met zonovergoten terrassen die uitkijken over het achterland en de skyline van de oude stad. Een dramatische, glanzend rode eettafel zet de toon voor glamoureuze avonden, terwijl het zwembadterras met zijn giraffenbeeld voor een onmiskenbare vakantiesfeer zorgt.',
 array['Privézwembad met zonneterras en uitzicht over het achterland','Vijf minuten van Ibiza-Stad en Pacha','Loopafstand tot Talamanca Beach','Opvallend eetterras met statement-tafel, plaats voor 12+','Zeven slaapkamers over vijf niveaus','Kunstzinnige, galerie-achtige interieurs','Volledig uitgeruste keuken','Meerdere lounge- en chill-out plekken, binnen en buiten'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/villa-prada/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/villa-prada/hero.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/pool-aerial.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/pool-dusk.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/outdoor-dining.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/bedroom-2.jpg','https://solaceexecutive.com/assets/photos/villas/villa-prada/bathroom.jpg'],
 40),

('Villa Jondal', 'Cala Jondal', 13, 17, 25, true, 1300, 50000,
 'Hoog boven een privébaai in Cala Jondal ligt Villa Jondal, een weids landgoed verspreid over drie gebouwen, verbonden door tropische tuinen, stenen paden en glooiende gazons. Binnen combineren en-suite slaapkamers en hoge leefruimtes historisch karakter met eigentijds design. Naast de twee zwembaden vinden gasten een eigen wellnesspaviljoen, een volledig uitgeruste sportschool, een buitenkeuken en zelfs een eigen clubruimte, allemaal verzorgd door voltijds personeel in de stijl van een boetiekhotel.',
 array['Twee zwembaden met panoramisch zeezicht','Directe toegang tot het strand beneden de villa','Eigen wellnesspaviljoen met massagebehandelingen','Volledig uitgeruste buiten-fitnessruimte','Eetpaviljoen voor tot 80 gasten','Eigen club-lounge met bar','Buitenkeuken en barbecuepaviljoen','Verzorgde tropische tuinen met Balinese loungeplekken','Parkeerplaats voor 20 auto''s'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/villa-jondal/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/villa-jondal/hero.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/pool.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/dining-terrace.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/bedroom-2.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/bathroom.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/pool-2.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/terrace.jpg','https://solaceexecutive.com/assets/photos/villas/villa-jondal/view.jpg'],
 50),

('Villa Majestic', 'Can Sire, bij Jesús / Ibiza-Stad', 3, 2, 6, true, 200, 700,
 'Een moderne, minimalistische villa in een rustige woonwijk op slechts drie kilometer van Ibiza-Stad, dichtbij genoeg om het nachtleven van het eiland in te lopen, maar privé achter een eigen omheinde tuin. Ruime, lichte kamers openen naar een omheind zwembadterras met Balinees daybed en verschillende chill-out hoeken, ideaal voor een groep vrienden of familie die ruimte wil om zich te verspreiden.',
 array['Privézwembad en omheinde tuin','Balinees daybed en chill-out hoeken','Airconditioning door het hele huis','Privéparkeren voor 2-3 auto''s','Volledig uitgeruste keuken','Rustige woonwijk, geen doorgaand verkeer','3 km van Ibiza-Stad en het nachtleven'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/villa-majestic/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/villa-majestic/hero.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/pool.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/pool-loungers.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/dining.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/bedroom-2.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/bathroom.jpg','https://solaceexecutive.com/assets/photos/villas/villa-majestic/bathroom-view.jpg'],
 60),

('Hacienda Puig Redo', 'Zuid-Ibiza', 10, 16, 25, true, 1200, 25000,
 'Gelegen op een ommuurd en afgesloten landgoed van 25.000 m² aan de zuidkant van Ibiza, is dit een van de grootste en meest complete landhuizen van het eiland, met eeuwenoud Ibicenco karakter en compromisloos modern comfort. Tien weelderige suites, weidse aangelegde tuinen en een clubruimte op resortniveau vormen samen een villa gebouwd voor totale privacy en moeiteloos entertainen, met uitzicht over dennenbos, de Middellandse Zee en Formentera. Van het verwarmde zwembad en de tennisbaan tot een eigen muziekkamer met DJ-booth, elk detail is afgestemd op lange, ontspannen verblijven met familie of vrienden. Er is daarnaast een volledig zelfstandig gastenverblijf met 3 extra en-suite slaapkamers.',
 array['Verwarmd zoutwaterzwembad met aparte buitenjacuzzi','Volwaardige tennisbaan en jeu-de-boulesbaan','Wellnessruimte met infraroodsauna, stoomcabine en fitnessruimte','Eigen muziekkamer ("The Club") met dansvloer, bar en DJ-booth','Overdekt eetpaviljoen voor tot 30 gasten, met professionele buitenkeuken','Eigen chef-kok en sommelier op aanvraag','Zelfstandig gastenverblijf met 3 extra en-suite slaapkamers','Weids aangelegde tuinen met eeuwenoude bomen','Volledig ommuurd landgoed van 25.000 m² voor optimale privacy','Glasvezel wifi en vloerverwarming door het hele huis'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/hero.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/pool-view.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/outdoor-club.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/guesthouse.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/grounds.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/tennis-court.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/music-room.jpg','https://solaceexecutive.com/assets/photos/villas/hacienda-puig-redo/bar-lounge.jpg'],
 70),

('Can Bellotera', 'Landelijk Ibiza', 6, 5, 14, true, 400, 5000,
 'Can Bellotera ligt op een landelijk perceel van vijfduizend vierkante meter, met een terracotta dak en booggewelfde galerij omringd door sinaasappelbomen en glooiende heuvels. Binnen stromen zonovergoten woonruimtes met terracotta vloeren door naar rondlopende terrassen en een weids zwembadterras van natuursteen. Met vijf tweepersoonskamers en een privé gastenappartement, goed voor veertien gasten in totaal, is dit huis gemaakt voor een grote familie of groep die ruimte, rust en een authentiek stukje landelijk Ibiza zoekt.',
 array['Groot privézwembad in een aangelegde tuin met ligstoelen','Airconditioning in elke slaapkamer','Drie aparte loungeruimtes plus een eigen eetkamer','Twee volledig uitgeruste keukens','Overdekte terrassen en balkons met uitzicht op het landschap','Buiten barbecueplek','Wifi en kluis op de kamer','Omringd door sinaasappel- en olijfbomen voor volledige privacy'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/can-bellotera/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/can-bellotera/hero.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/terrace.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/pool.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/view.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/dining-room.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/bedroom-2.jpg','https://solaceexecutive.com/assets/photos/villas/can-bellotera/bathroom.jpg'],
 80),

('Villa Deseo', 'Can Furnet', 8, 8, 20, true, 800, 17000,
 'Hoog boven Ibiza-Stad in Can Furnet combineert Villa Deseo acht sfeervolle en-suite slaapkamers met een lagune-vormig zwembad, los van het hoofdhuis voor optimale privacy, omgeven door zeventienduizend vierkante meter tuinen en dennenbos. Twee grote terrassen bieden dineren buiten voor zestien personen onder geweven hanglampen, terwijl een dakjacuzzi en een eigen tennisbaan het geheel compleet maken. Ononderbroken uitzicht over Dalt Vila, Formentera en de haven maken dit een unieke combinatie van nabijheid tot de stad en volledige afzondering.',
 array['Lagune-vormig zwembad, los van het huis voor extra privacy','Dakjacuzzi met zonsondergang-uitzicht','Eigen volwaardige tennis-/basketbalbaan','Houtoven voor pizza''s en asados','Eettafel buiten voor 16 personen, plus biljarttafel en vleugel','Panoramisch uitzicht op Dalt Vila, Formentera en de haven','Conciërgeservice en dagelijkse schoonmaak inbegrepen','Volledig privé, geen buren in zicht, 5 minuten van Ibiza-Stad en Pacha'],
 null,
 'https://solaceexecutive.com/assets/photos/villas/villa-deseo/hero.jpg',
 array['https://solaceexecutive.com/assets/photos/villas/villa-deseo/hero.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/aerial.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/pool-view.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/pool-night.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/lounge-terrace.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/dining.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/living-room.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/kitchen.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/bedroom-1.jpg','https://solaceexecutive.com/assets/photos/villas/villa-deseo/bathroom.jpg'],
 90);
